### ISSUE TITLE
Putting a dom-bind template inside a `demo-snippet` causes the demo element to double

### ISSUE THREAD

**Issue by beatbits** [PolymerElements/iron-demo-helpers#30] opened 2016-05-04 14:10 UTC
### Description
Putting a dom-bind template inside a `demo-snippet` causes the demo element to double

### Expected outcome
To be render as normal with data-binding

### Actual outcome
Double elements on the demo

### Live Demo
http://jsbin.com/qefide/edit?html,output

### Steps to reproduce

1. Put a `dom-bind template` element inside an `demo-snippet` element.
2. See that the element which you want to be on the demo is doubled.

### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10
I think it affects all browsers

**Comment by carolirod** [comment] 2016-05-05 12:26
+1

**Comment by cells-developers** [comment] 2016-05-05 12:27
+1

**Comment by abdonrd** [comment] 2016-05-05 14:02
+1

**Comment by notwaldorf** [comment] 2016-05-31 17:53
Closing as a duplicate of https://github.com/PolymerElements/iron-demo-helpers/issues/29, will respond there :)

**Closed by notwaldorf** 2016-05-31 17:53 UTC
